spring:
  application:
    name: BankCardsApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: Mardali
    password: Mardali
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/migration/changelog.yaml
    default-schema: public

  doc:
    swagger-ui:
      path: /swagger-ui.html
      tagsSorter: alpha
      operationsSorter: alpha
    api-docs:
      path: /api-docs

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  jwt:
    secret: your-secret-key-here-make-it-long-and-secure-for-production
    expiration: 86400000 # 24 hours in milliseconds

  cors:
    allowed-origins: "http://localhost:3000,http://localhost:4200" # фронтенд
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "Authorization,Content-Type"
    allow-credentials: true
